### ISSUE TITLE
search.json not being generated

### ISSUE THREAD

**Issue by claman** [yortz/octopress-lunr-js-search#2]
There are no errors being generated that I can see (at least not with `rake generate --trace`). I've added all of the files in the correct directories, added liquid tags to the proper files, and changed _config.yml to generate using lunr-search instead of simple search. I haven't changed any of the files in any way.

**Comment by yortz** [comment]
That's weird, you are the first reporting this kind of issue, have you tried running the tests? I'll keep an eye on this see if I can replicate the same behaviour.

**Comment by claman** [comment]
I'm getting some weird errors when I try to run the test. Running `guard start` does this:

```
WARN: Unresolved specs during Gem::Specification.reset:
listen (~> 2.7)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require': cannot load such file -- hitimes/hitimes (LoadError) from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1@global/gems/hitimes-1.2.1/lib/hitimes.rb:37:in `rescue in <top (required)>'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1@global/gems/hitimes-1.2.1/lib/hitimes.rb:32:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1@global/gems/timers-2.0.0/lib/timers.rb:4:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1@global/gems/celluloid-0.16.0.pre/lib/celluloid/receivers.rb:2:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1@global/gems/celluloid-0.16.0.pre/lib/celluloid.rb:475:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/gems/listen-2.7.9/lib/listen.rb:1:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/gems/guard-2.6.1/lib/guard/setuper.rb:2:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/gems/guard-2.6.1/lib/guard.rb:13:in `<top (required)>'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/gems/guard-2.6.1/bin/guard:3:in `<top (required)>'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/bin/guard:23:in `load'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/bin/guard:23:in `<main>'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
from /Users/alexclaman/.rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by yortz** [comment]
You are not forced to use guard to run the specs. Guard is meant to automate tests. You can run tests by running `jasmine-headless-webkit` in your terminal. At the moment I am not able to replicate the issue you are experiencing, it seems that with me the json file got generated each time and updated with contents of new content. Have you by chance modified octopress default install folder structure?

**Comment by claman** [comment]
I don't remember changing the default folder structure, but I'm going to go ahead and try a new, completely clean install of Octopress to see if that works.

**Comment by yortz** [comment]
ok, keep me posted

**Comment by claman** [comment]
Well, I don't think it explains why the json file isn't being generated, but I can't seem to escape errors involving jekyll-assets. I'll try to troubleshoot those first.

Also, regardless of the fact that guard didn't work, running `rake preview` within the testing directory did generate a search.json. So I really have no idea what's going on.

**Comment by yortz** [comment]
Well `rake preview` watches, and mounts a webserver at `http://localhost:4000`. Have you tried `rake generate` ? I think that it would be reasonable to first try to fix the issues you are experiencing with jekyll-assets plugin since I am using it to compile coffeescript to js. Maybe you can open an issue or ask the mantainer of the jekyll-assets repo. Installling jekyll-assets is not so straightforward but can be easily achieved by following the advice (in the README) from [this](http://matt.coneybeare.me/how-to-setup-a-rails-like-asset-pipeline-with-octopress/) blog post.

**Comment by claman** [comment]
Yeah, I meant `rake generate`. My bad.

I actually just opened an issue. I've been trying to follow the process outlined in that blog post, but to no avail..

**Comment by ghost** [comment]
@claman did you ever get around this? I am seeing the `search.json` file while `rake generate` is running, but it gets deleted just before finishing

**Comment by claman** [comment]
@nbalonso sadly no. I got frustrated enough that I gave up trying. I did eventually get jekyll-assets working though.
